name: 'publish'
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node ./scripts/cicd/fail-if-version-tag-exists.js --current
        name: Version must not already be tagged
        working-directory: .

      - run: npm ci
        name: Install

      - run: node ./scripts/cicd/write-version-to-file-and-github-output.js ${{ github.run_number }}
        name: Get version and write to environment
        # outputs: VERSION
        # outputs: PACKAGE_VERSION
        id: get-version
        working-directory: .

      - run: npm run build
        name: Build

      - run: npm run migrate:cicd -- --execute
        name: Migrate
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

